export { default as HomePage } from "./HomePage"
export { default as ServicesPage } from "./ServicesPage"
export { default as ForHomePage } from "./ForHomePage"
export { default as ForFlatPage } from "./ForFlatPage"
export { default as ProjectsPage } from "./ProjectsPage"
export { default as ContactsPagePage } from "./ContactsPage"
export { default as NotWorkingPage } from "./NotWorkingPage"
